version: '3.4'

services:
  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  basket.db:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  
