version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4

  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  basket.db:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  discount.db:
    image: postgres

  discount.api:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount/Discount.Grpc/Dockerfile
      
  order.db:
    image: mcr.microsoft.com/azure-sql-edge

  order.api:
    image: ${DOCKER_REGISTRY-}order
    build:
      context: .
      dockerfile: Ordering/Ordering.API/Dockerfile
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

